In [1]:
import numpy as np

In [2]:
arr = np.array ([24,27,29,88,99,44,55])
arr

array([24, 27, 29, 88, 99, 44, 55])

In [3]:
arr.dtype

dtype('int32')

In [7]:
arr = np.array ([24,27,29,88,99,44,55])
arr

array([24, 27, 29, 88, 99, 44, 55])

In [8]:
arr.dtype

dtype('int32')

In [6]:
arr.ndim

1

In [10]:
arr.size

7

In [14]:
arr

array([24, 27, 29, 88, 99, 44, 55])

In [15]:
# arr.min()
# arr.max()
# arr.sum()
# arr.mean()


52.285714285714285

In [17]:
arr2 = np.arange(1,21)
arr2
# single dimension array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
arr2[-1]  =   500

In [21]:
arr2 

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19, 500])

In [22]:
arr2 + 5 

array([  6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19,  20,  21,  22,  23,  24, 505])

In [23]:
arr2

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19, 500])

In [25]:
arr = np.arange(1,61)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [40]:
lst = [[1,2,3],[4,5,6],[7,8,9]]
lst 

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [58]:
lst[1][1]

5

In [57]:
arr = np.array(lst)
arr[:2,:2]

array([[1, 2],
       [4, 5]])

In [60]:
# 4 dimension 
arr[1][1]

5

In [61]:
arr[1,1]

5

In [62]:
arr.shape

(3, 3)

In [66]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
arr[1:2,2:]

array([[6]])

In [97]:
# arr[row_start:row_stop:row_step   ,   row_start:row_stop:row_step]
arr[2:3,2]  =  500

In [98]:
arr 

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8, 500]])

In [91]:
arr[-1,-1]

9

In [100]:
arr[-1][-1]  = 9 

In [101]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr = np.array ([24,27,29,88,99,44,55])
arr

In [103]:
arr[2:3,2][0]

9

In [104]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
arr[:3,2]

array([3, 6, 9])

In [133]:
arr[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [142]:
for row in arr:
    for  i in row:
        print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
1. 5 present is present or not 
2. if present then position of 5 
3. find out the sum of 2d array but row wise output = [1,2,3]
4. count no. of even row wise .
5. print all element greater than 25, and also print all number which are divisible by 7 in each row.


In [144]:
arr = np.arange(1,61).reshape((12,5))
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60]])

In [145]:
#5 is present 

for row in arr:
    for i  in row:
        if i==5:
            print("number is there")
        else:
            print("number is not there")

number is not there
number is not there
number is not there
number is not there
number is there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
numb

In [146]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60]])

In [147]:
# position 
for row in arr:
    for i in row:
        

array([5])

In [148]:
#3
for row in arr:
    sum = np.sum(row)
    print(sum)

15
40
65
90
115
140
165
190
215
240
265
290


In [151]:
#4
for row in arr:
    for i in row:
        if i%2==0:
            print("even no",i)

even no 2
even no 4
even no 6
even no 8
even no 10
even no 12
even no 14
even no 16
even no 18
even no 20
even no 22
even no 24
even no 26
even no 28
even no 30
even no 32
even no 34
even no 36
even no 38
even no 40
even no 42
even no 44
even no 46
even no 48
even no 50
even no 52
even no 54
even no 56
even no 58
even no 60


In [152]:
#5
for row in arr:
    for i in row:
        if i>25 and i%7==0:
            print(i)

28
35
42
49
56


In [1]:
import numpy as np

In [2]:
arr= np.arange(1,91)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90])

In [3]:
arr.reshape(30,3)   #reshape in 2d array


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33],
       [34, 35, 36],
       [37, 38, 39],
       [40, 41, 42],
       [43, 44, 45],
       [46, 47, 48],
       [49, 50, 51],
       [52, 53, 54],
       [55, 56, 57],
       [58, 59, 60],
       [61, 62, 63],
       [64, 65, 66],
       [67, 68, 69],
       [70, 71, 72],
       [73, 74, 75],
       [76, 77, 78],
       [79, 80, 81],
       [82, 83, 84],
       [85, 86, 87],
       [88, 89, 90]])

In [4]:
#reshape in 3d array
arr = np.arange(1,301)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [6]:
arr2 = arr.reshape(4,15,5)
arr2

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25],
        [ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75]],

       [[ 76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100],
        [101, 102, 103, 104, 105],
        [106, 107, 108, 109, 110],
        [111, 112, 113, 114, 115],
        [116, 117, 118, 119, 120],
        [121, 122, 123, 124, 125],
        [126, 127, 128, 129, 130],
        [131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140],
        [141, 142,

In [7]:
arr2.shape
#(4, 15, 5) -->  (table,row,column)

(4, 15, 5)

In [8]:
arr2[:,0:2,:]

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10]],

       [[ 76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85]],

       [[151, 152, 153, 154, 155],
        [156, 157, 158, 159, 160]],

       [[226, 227, 228, 229, 230],
        [231, 232, 233, 234, 235]]])

In [12]:
arr2[:,-1,-1] # slicing of 3d array [table,row,column]

array([ 75, 150, 225, 300])

In [13]:
arr2.flatten()   #convert into 1D array 

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [14]:
arr2.ravel()   # same as flatten


array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [16]:
arr= np.arange(1,61).reshape(15,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40],
       [41, 42, 43, 44],
       [45, 46, 47, 48],
       [49, 50, 51, 52],
       [53, 54, 55, 56],
       [57, 58, 59, 60]])

In [19]:
arr.transpose().shape
#arr.T.shape       we can write like this 

(4, 15)

In [20]:
np.zeros((15,4))    # make a dummy matrix conmtaining zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((5,5))    # make a dummy matrix conmtaining ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.linspace(1,3,10) #in between 1 to 5 and 9 elements use to make matrix in a range

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [25]:
np.linspace(1,5,30).reshape(15,2)

array([[1.        , 1.13793103],
       [1.27586207, 1.4137931 ],
       [1.55172414, 1.68965517],
       [1.82758621, 1.96551724],
       [2.10344828, 2.24137931],
       [2.37931034, 2.51724138],
       [2.65517241, 2.79310345],
       [2.93103448, 3.06896552],
       [3.20689655, 3.34482759],
       [3.48275862, 3.62068966],
       [3.75862069, 3.89655172],
       [4.03448276, 4.17241379],
       [4.31034483, 4.44827586],
       [4.5862069 , 4.72413793],
       [4.86206897, 5.        ]])

In [26]:
import random

In [27]:
random.randint(1,5)

4

In [28]:
np.random.randint(1,5,9)

array([3, 1, 2, 4, 2, 2, 3, 3, 1])

In [29]:
np.random.randint(1,5,(5,4))

array([[4, 1, 4, 1],
       [1, 2, 2, 2],
       [2, 3, 2, 3],
       [3, 2, 1, 1],
       [1, 3, 1, 3]])

In [33]:
np.random.random((5,4))

array([[0.02600101, 0.37138326, 0.71489287, 0.61947656],
       [0.9326966 , 0.37722921, 0.95771758, 0.29474528],
       [0.42067763, 0.88810574, 0.70843386, 0.19082703],
       [0.06810104, 0.37033241, 0.48849931, 0.53413705],
       [0.21919958, 0.11791243, 0.31217435, 0.94141148]])

In [39]:
arr= np.random.randint(1,10,10)
arr

array([2, 1, 9, 6, 8, 4, 4, 6, 2, 7])

In [48]:
np.random.choice(arr)       #randomly choose a number from the given array in the parameter



8

In [49]:
np.random.choice(np.array(list(range(1,101))))

76

In [72]:
arr = np.random.randint(1,25,20)
arr

array([ 2, 12,  3, 23,  3,  2,  5, 10,  1, 21, 17, 14, 20, 18,  2, 19, 11,
        7, 24,  1])

In [52]:
# arr.max()
# np.argmax(arr)  # it returns the index position of the max element
# np.argmin(arr)   # It returns the index position of the min




13

In [60]:
# arr.sort()
arr.sort()

In [70]:
arr[::-1]    # sort in descending order

array([23, 22, 22, 19, 18, 18, 18, 17, 14, 14, 12, 12, 11, 10, 10,  9,  8,
        8,  7,  1])

In [73]:
arr

array([ 2, 12,  3, 23,  3,  2,  5, 10,  1, 21, 17, 14, 20, 18,  2, 19, 11,
        7, 24,  1])

In [74]:
np.argsort(arr) # it gives sorted index


array([19,  8, 14,  5,  0,  2,  4,  6, 17,  7, 16,  1, 11, 10, 13, 15, 12,
        9,  3, 18], dtype=int64)

In [75]:
arr = arr.ravel()
arr

array([ 2, 12,  3, 23,  3,  2,  5, 10,  1, 21, 17, 14, 20, 18,  2, 19, 11,
        7, 24,  1])

In [76]:
arr1= np.random.randint(1,20,10)
arr2= np.random.randint(1,20,10)


In [77]:
arr1

array([ 8, 11, 19,  6, 16, 18,  7, 18, 18,  5])

In [78]:
arr2

array([14,  7,  6, 11,  1, 16,  2, 17, 10,  4])

In [79]:
arr1= np.random.randint(1,5,4)
arr2= np.random.randint(1,10,(5,4))


In [80]:
arr1

array([3, 2, 4, 4])

In [81]:
arr2

array([[7, 6, 6, 7],
       [9, 6, 4, 6],
       [3, 8, 5, 7],
       [5, 4, 5, 9],
       [1, 6, 2, 4]])