In [1]:
import numpy as np

In [2]:
arr = np.array ([24,27,29,88,99,44,55])
arr

array([24, 27, 29, 88, 99, 44, 55])

In [3]:
arr.dtype

dtype('int32')

In [7]:
arr = np.array ([24,27,29,88,99,44,55])
arr

array([24, 27, 29, 88, 99, 44, 55])

In [8]:
arr.dtype

dtype('int32')

In [6]:
arr.ndim

1

In [10]:
arr.size

7

In [14]:
arr

array([24, 27, 29, 88, 99, 44, 55])

In [15]:
# arr.min()
# arr.max()
# arr.sum()
# arr.mean()


52.285714285714285

In [17]:
arr2 = np.arange(1,21)
arr2
# single dimension array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
arr2[-1]  =   500

In [21]:
arr2 

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19, 500])

In [22]:
arr2 + 5 

array([  6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19,  20,  21,  22,  23,  24, 505])

In [23]:
arr2

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19, 500])

In [25]:
arr = np.arange(1,61)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [40]:
lst = [[1,2,3],[4,5,6],[7,8,9]]
lst 

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [58]:
lst[1][1]

5

In [57]:
arr = np.array(lst)
arr[:2,:2]

array([[1, 2],
       [4, 5]])

In [60]:
# 4 dimension 
arr[1][1]

5

In [61]:
arr[1,1]

5

In [62]:
arr.shape

(3, 3)

In [66]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
arr[1:2,2:]

array([[6]])

In [97]:
# arr[row_start:row_stop:row_step   ,   row_start:row_stop:row_step]
arr[2:3,2]  =  500

In [98]:
arr 

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8, 500]])

In [91]:
arr[-1,-1]

9

In [100]:
arr[-1][-1]  = 9 

In [101]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr = np.array ([24,27,29,88,99,44,55])
arr

In [103]:
arr[2:3,2][0]

9

In [104]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
arr[:3,2]

array([3, 6, 9])

In [133]:
arr[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [142]:
for row in arr:
    for  i in row:
        print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
1. 5 present is present or not 
2. if present then position of 5 
3. find out the sum of 2d array but row wise output = [1,2,3]
4. count no. of even row wise .
5. print all element greater than 25, and also print all number which are divisible by 7 in each row.


In [144]:
arr = np.arange(1,61).reshape((12,5))
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60]])

In [145]:
#5 is present 

for row in arr:
    for i  in row:
        if i==5:
            print("number is there")
        else:
            print("number is not there")

number is not there
number is not there
number is not there
number is not there
number is there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
number is not there
numb

In [146]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60]])

In [147]:
# position 

arr[0:1,4]

array([5])

In [148]:
#3
for row in arr:
    sum = np.sum(row)
    print(sum)

15
40
65
90
115
140
165
190
215
240
265
290


In [151]:
#4
for row in arr:
    for i in row:
        if i%2==0:
            print("even no",i)

even no 2
even no 4
even no 6
even no 8
even no 10
even no 12
even no 14
even no 16
even no 18
even no 20
even no 22
even no 24
even no 26
even no 28
even no 30
even no 32
even no 34
even no 36
even no 38
even no 40
even no 42
even no 44
even no 46
even no 48
even no 50
even no 52
even no 54
even no 56
even no 58
even no 60


In [152]:
#5
for row in arr:
    for i in row:
        if i>25 and i%7==0:
            print(i)

28
35
42
49
56
